# NumPy - Numerical Python Library

In [1]:
#Import Numpy Library

import numpy as np

In [2]:
#create simple array from the list

arr = np.array([[1,2,3,4],[5,6,7,8]])
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [3]:
#diamension of the array

print(arr.ndim)

2


In [4]:
#shape of the array

print(arr.shape)

(2, 4)


In [5]:
#diamension of the array

print(type(arr))

<class 'numpy.ndarray'>


In [6]:
#diamension of the array

print(arr.data)

# Random Number Generator using numpy

In [10]:
from numpy import random
x= random.randint(100)
print(x)

0


In [22]:
#Generate Random Float

x= random.rand(10)
print(x)

[0.88085851 0.92420967 0.34901654 0.4710092  0.54105983 0.56192244
 0.04052399 0.00740748 0.94061563 0.21736616]


In [25]:
#3.	Generate Random Array

from numpy import random
x= random.randint(100, size=(5))
print(x)

[78 54 11  4 87]


In [47]:
#Generate a 2-D array with 3 rows, each row containing 5 random integers from 0 to 100

from numpy import random
random.seed(101)
x= random.randint(100, size=(3, 5))
print(x)


[[95 11 81 70 63]
 [87 75  9 77 40]
 [ 4 63 40 60 92]]


# 2.4 PRACTICAL:  Creating scalars in Numpy

In [48]:
#numpy.asscaler()

import numpy as np

in_arr = np.array([8])

print("input array is ", in_arr)

out_scalar = np.asscalar(in_arr)
print("output scalar from input array ", out_scalar)


input array is  [8]
output scalar from input array  8


C:\Users\DEGREE\AppData\Local\Temp\ipykernel_6200\417224096.py:9: DeprecationWarning: np.asscalar(a) is deprecated since NumPy v1.16, use a.item() instead
  out_scalar = np.asscalar(in_arr)


# 2.5 PRACTICAL:  Creating Vector in Numpy

In [49]:
#import numpy

import numpy as np

#creating 1-D list
list1 = [1, 2, 3]

#creating 1-D list vertical

list2 = [[10],
        [20],
        [30]]

#create vector1

vector1 =  np.array(list1)
vector2 = np.array(list2)

print("Horizontal Vector")
print(vector1)

print("------------------")

print("Vectical Vector")
print(vector2)



Horizontal Vector
[1 2 3]
------------------
Vectical Vector
[[10]
 [20]
 [30]]


# 2.6 PRACTICAL Creating Matrix in Numpy

In [51]:
import numpy as np

a=np.matrix('1 2; 3 4')
print("via string input : \n", a, "\n\n")

#array-like input
b = np.matrix([[5, 6, 7], [4, 6]])
print("via array-like input :\n", b)

via string input : 
 [[1 2]
 [3 4]] 


via array-like input :
 [[list([5, 6, 7]) list([4, 6])]]


C:\Users\DEGREE\anaconda3\lib\site-packages\numpy\matrixlib\defmatrix.py:145: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr = N.array(data, dtype=dtype, copy=copy)


In [50]:
a=np.matrix('1 2; 3 4')
a

matrix([[1, 2],
        [3, 4]])

# 2.7 PRACTICAL:  Matrix Multiplication in Numpy

In [52]:
import numpy as np

A = 5

B = [[6, 7],
      [8, 9]]
 
print(np.dot(A,B))

[[30 35]
 [40 45]]


In [53]:
import numpy as np

A = [[6, 7],
      [8, 9]]
      
B = [[1, 3],
      [5, 7]]

print(np.dot(A,B))

print("----------")

print(np.dot(B,A))

[[41 67]
 [53 87]]
----------
[[30 34]
 [86 98]]


In [62]:
A= ([1,2,3],[4,5,6],[7,8,9])

np.transpose(A)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

# 2.8 PRACTICAL:  Measure of Central Tendency Using Numpy

In [ ]:
import numpy as np

arr = np.array([[1,23,78], [98,60,75],[79,25,48]])
print(arr)

#min function
print(np.amin(arr))
#max function
print(np.amax(arr))


In [ ]:
#2.	Finding Mean, Median, Standard Deviation and Variance in NumPy
a = np.array([5,6,7])
print(a)
print("mean of array a =",np.mean(a))
print("median of array a =",np.median(a))
print("standard deviation of array a =",np.std(a))
print("Variance of array a =",np.var(a))

# 2.9 PRACTICAL:  Percentile & Interquartile in Numpy

In [6]:
import numpy as np
data = [32, 36, 46, 47, 56, 69, 75, 79, 79, 88, 89, 91, 92,93, 96, 97,101,105,112,116]

#first quartile(Q1)

Q1 = np.median(data[:10])
print(Q1, '\n')
#third Quartile
Q3 = np.median(data[10:])
print(Q3, '\n')
#interquartile range

IQR = Q3-Q1

print("IQR = Q3-Q1 = ", IQR)


62.5 

96.5 

IQR = Q3-Q1 =  34.0


# 2.10 PRACTICAL:  Array Broadcasting in Numpy

In [ ]:
a = np.array([1.0, 2.0, 3.0])
b = np.array([2.0, 2.0, 2.0])

a * b

In [ ]:
a = np.array([1.0, 2.0, 3.0])
b = 2.0

a * b